### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by ryyppy** [steelsojka/deoplete-flow#1]
Hey!
Any directions on how to install this deoplete plugin?

I didn't find any documentation on how to install those properly... also the last commit message tells me that this project is in a WIP state ... would be happy to help testing and documenting things :-)

**Comment by steelsojka** [comment]
Yeah this was just an experiment to see if I could get it working. I want to refine it a bit more, but it SHOULD just work with any vim plugin manager (pathogen, vim-plugged, etc...). I'm using vim-plugged and it should work.

**Comment by ryyppy** [comment]
Got ya, took me a while to understand how the plugin system of deoplete works, now I created a PR with some added functionality :-)
