### ISSUE TITLE
differences with deoplete-ternjs?

### ISSUE THREAD

**Issue by nhooyr** [steelsojka/deoplete-flow#7]
What are the differences between flow and ternjs?

**Comment by steelsojka** [comment]
@nhooyr You can google the differences, but flow is a static type system designed to statically analyze types in Javascript (Similar to TypeScript's types but not the same). It's meant to be used with a transpiler like babel that will strip the types for runtime. TernJS is an analyzer for Javascript code, but does not offer typings like flow. You can find better explanations online but that is the high level differences.
